version: "3.3"
services:
    kingland-website:
        build: 
            dockerfile: Dockerfile
        ports:
            - "80:80"
            - "443:443"
        restart: "always"
        image: kingland-website
